### ISSUE TITLE
[BUG] Can't handle scroll id longer than 4096 bytes.

### ISSUE THREAD

**Issue by Pablosko98** [opensearch-project/opensearch-js#349] opened 2022-12-21 16:44 UTC
### What is the bug?
opensearch-js doesn't handle scroll IDs longer than 4096.

The scroll API encodes the scroll ID as part of the URL (https://github.com/opensearch-project/opensearch-js/blob/main/api/api/scroll.js#L79). This is actively discouraged (even deprecated) by elastic https://www.elastic.co/guide/en/elasticsearch/reference/current/scroll-api.html#scroll-api-query-params and should be sent as a body parameter.
```
Scroll IDs can be long. We recommend only specifying scroll IDs using the [scroll_id request body parameter](https://www.elastic.co/guide/en/elasticsearch/reference/current/scroll-api.html#scroll-api-scroll-id-param).
```
Full error that I got:
```
{
    "name": "ResponseError",
    "meta": {
        "body": {
            "error": {
                "root_cause": [
                    {
                        "type": "too_long_http_line_exception",
                        "reason": "An HTTP line is larger than 4096 bytes."
                    }
                ],
                "type": "too_long_http_line_exception",
                "reason": "An HTTP line is larger than 4096 bytes."
            },
            "status": 400
        },
        "statusCode": 400,
        "headers": {
            "content-type": "application/json; charset=UTF-8",
            "content-length": "219"
        },
        "meta": {
            "context": null,
            "request": {
                "params": {
                    "method": "GET",
                    "path": "/_search/scroll/FGluY2x1ZGVfY29udGV ... FQcXc%3D",
                    "body": "",
                    "querystring": "",
                    "headers": {
                        "user-agent": "opensearch-js/2.1.0 (linux 4.15.0-197-generic-x64; Node.js v18.12.1)"
                    },
                    "timeout": 30000
                },
                "options": {},
                "id": 9
            },
            "name": "opensearch-js",
            "connection": {
                "url": <url>,
                "id": <id>
                "headers": {},
                "deadCount": 0,
                "resurrectTimeout": 0,
                "_openRequests": 0,
                "status": "alive",
                "roles": {
                    "data": true,
                    "ingest": true
                }
            },
            "attempts": 0,
            "aborted": false
        }
    }
}
```

### How can one reproduce the bug?
Feed a longer tan 4096 character scroll id to the opensearch-js client

### What is the expected behavior?
The client handles scroll IDs of any length appropriately

### What is your host/environment?
```
opensearch-js: opensearch-js/2.1.0
OS: linux 4.15.0-197-generic-x64
Node.js v18.12.1
```

**Comment by wbeckler** [comment] 2022-12-21 17:40
It sounds like the issue is that scroll IDs need to be accepted as body parameters, since the URL-based method is going to break due to the http protocol. 

This makes sense. Feel free to contribute a PR to add this ability.

**Comment by Pablosko98** [comment] 2022-12-23 10:26
It looks like accepting scroll ID as a body param is already supported.
So calling the client with `client.scroll({scroll_id: 'foo'})` will send scroll_id as part of the path but doing `client.scroll({body: { scroll_id: 'foo'}})` will send it as part of the body, which is the recommended approach.

I don't think there's any code changes required for us since we can use the `({body: {scroll_id}})` approach.

**Comment by wbeckler** [comment] 2022-12-28 15:47
closing

**Closed by wbeckler** 2022-12-28 15:47 UTC
